version: "2"
services:

  app:
    build: .
    command: "./docker_entrypoint.sh"
    container_name: "gatsby-starter-modern"
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    image: "gatsby-starter-modern"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

# volumes:
#   .: 
